//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokHaneV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabKullanici()
        {
            this.TabLogRasyon = new HashSet<TabLogRasyon>();
        }
    
        public int idKullanici { get; set; }
        public string KulAdi { get; set; }
        public string kulisim { get; set; }
        public string kulsoyisim { get; set; }
        public string eposta { get; set; }
        public string tel { get; set; }
        public int idyetki { get; set; }
        public System.DateTime sonerisim { get; set; }
        public string kulsif { get; set; }
    
        public virtual TabYetki TabYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabLogRasyon> TabLogRasyon { get; set; }
    }
}
