//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokHaneV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabLogRasyon
    {
        public int idislem { get; set; }
        public int idRasyon { get; set; }
        public int idRasyonTarif { get; set; }
        public int İdHane { get; set; }
        public int idKullanici { get; set; }
        public System.DateTime islemTarihi { get; set; }
    
        public virtual TabHane TabHane { get; set; }
        public virtual TabKullanici TabKullanici { get; set; }
        public virtual TabRasyon TabRasyon { get; set; }
        public virtual Tabrasyontarifi Tabrasyontarifi { get; set; }
    }
}
