//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokHaneV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabRasyon()
        {
            this.TabLogRasyon = new HashSet<TabLogRasyon>();
            this.Tabrasyontarifi = new HashSet<Tabrasyontarifi>();
        }
    
        public int idRasyon { get; set; }
        public string RasyonAdi { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<int> idkullanici { get; set; }
    
        public virtual TabKullanici TabKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabLogRasyon> TabLogRasyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabrasyontarifi> Tabrasyontarifi { get; set; }
    }
}
