//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokHaneV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabUrunGenel
    {
        public int idurungenel { get; set; }
        public int idUrun { get; set; }
        public int idirsaliye { get; set; }
        public double miktar { get; set; }
        public int idmiktarcins { get; set; }
        public int idalsatkul { get; set; }
    
        public virtual TabAlsatkul TabAlsatkul { get; set; }
        public virtual Tabirsaliye Tabirsaliye { get; set; }
        public virtual TabmiktarCins TabmiktarCins { get; set; }
        public virtual Taburun Taburun { get; set; }
    }
}
