//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokHaneV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taburun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taburun()
        {
            this.Tabrasyontarifi = new HashSet<Tabrasyontarifi>();
            this.TabUrunGenel = new HashSet<TabUrunGenel>();
        }
    
        public int idurun { get; set; }
        public string UrunAdi { get; set; }
        public string stokKod { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabrasyontarifi> Tabrasyontarifi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUrunGenel> TabUrunGenel { get; set; }
    }
}
